leftnav:
- identifier: 704dfff4-6898-eb91-bad9-4d56abc801bb
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: cafe3be0-95c7-3058-8ac5-35653346a561
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 95bb2032-3c5e-be70-c01a-3a9d7b21718c
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 44991dc8-e618-0f77-d393-37ffb82c6041
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: 750b3406-15ac-b201-d8fe-66f4315be220
  name: Projects
  url: /pages/projects
  weight: 50
